FROM node:20

RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /app

COPY package*.json ./

ENV NODE_ENV=prod

RUN npm install

COPY . .

CMD ["sh", "-c", "if [ \"$NODE_ENV\" = 'dev' ]; then npm run dev; else npm start; fi"]